### ISSUE TITLE
ImageData类型定义缺失

### ISSUE THREAD

**Issue by DazeCake** [arkntools/depot-recognition#2]
# 环境
`node: v18.16.0`
`OS: win11`

# 问题描述
在运行文档中给出的示例后，提示如下错误
```
PS C:\Users\DazeCake\Development\LittleHandy> node "c:\Users\DazeCake\Development\LittleHandy\app.js"
c:\Users\DazeCake\Development\LittleHandy\node_modules\@arkntools\depot-recognition\dist\index.js:380
  const imgData = new ImageData(new Uint8ClampedArray(img.bitmap.data), img.bitmap.width, img.bitmap.height);
                  ^

ReferenceError: ImageData is not defined
    at c:\Users\DazeCake\Development\LittleHandy\node_modules\@arkntools\depot-recognition\dist\index.js:380:19
    at Array.map (<anonymous>)
    at recognizeNumbers (c:\Users\DazeCake\Development\LittleHandy\node_modules\@arkntools\depot-recognition\dist\index.js:378:57)
    at DeportRecognizer.recognize (c:\Users\DazeCake\Development\LittleHandy\node_modules\@arkntools\depot-recognition\dist\index.js:546:30)
    at async c:\Users\DazeCake\Development\LittleHandy\app.js:29:22

Node.js v18.16.0
```
在vsc中尝试跳转可以跳转到位于本地路径`~\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\lib.dom.d.ts`中的此类型定义如下
```javascript
/** The underlying pixel data of an area of a <canvas> element. It is created using the ImageData() constructor or creator methods on the CanvasRenderingContext2D object associated with a canvas: createImageData() and getImageData(). It can also be used to set a part of the canvas by using putImageData(). */
interface ImageData {
    readonly colorSpace: PredefinedColorSpace;
    /** Returns the one-dimensional array containing the data in RGBA order, as integers in the range 0 to 255. */
    readonly data: Uint8ClampedArray;
    /** Returns the actual dimensions of the data in the ImageData object, in pixels. */
    readonly height: number;
    /** Returns the actual dimensions of the data in the ImageData object, in pixels. */
    readonly width: number;
}

declare var ImageData: {
    prototype: ImageData;
    new(sw: number, sh: number, settings?: ImageDataSettings): ImageData;
    new(data: Uint8ClampedArray, sw: number, sh?: number, settings?: ImageDataSettings): ImageData;
};
```
# 可能的解决措施
或许可以手动实现此类型？

**Comment by Tsuk1ko** [comment]
我的，不知道之前怎么想的 node 测试的时候直接造了一个 polyfill 但是没在代码里实现

![Sq9NiJvx](https://user-images.githubusercontent.com/24877906/234547117-05c62389-8f27-44af-82eb-78dd6aa27b08.png)

**Comment by Tsuk1ko** [comment]
fixed 2c1185153371cdd9686c780006e63eae7cccb0a0

等 v1.6.3
